# Generated by Django 5.0.1 on 2024-04-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_event_artist_event_description_event_event_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Tarpiya', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_end',
            field=models.TimeField(default='07:43:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_start',
            field=models.TimeField(default='07:43:00'),
        ),
    ]
